<div id="chat_extra_body_mapp_chats" style="display: none;"><iframe id="iframe_mapp_chats" name="iframe_mapp_chats" style="width: 100%; border: 0px;" src="../mapp/mapp_chats.php?ses=<?php echo $ses ?>&<?php echo $now ?>" scrolling="auto" border=0 frameborder=0></iframe></div>
<div id="chat_extra_body_mapp_traffic" style="display: none;"><iframe id="iframe_mapp_traffic" name="iframe_mapp_traffic" style="width: 100%; border: 0px;" src="about:blank" scrolling="auto" border=0 frameborder=0></iframe></div>
<div id="chat_extra_body_mapp_themes" style="display: none;"><iframe id="iframe_mapp_themes" name="iframe_mapp_themes" style="width: 100%; border: 0px;" src="about:blank" scrolling="auto" border=0 frameborder=0></iframe></div>
<div id="chat_extra_body_mapp_prefs" style="display: none;"><iframe id="iframe_mapp_prefs" name="iframe_mapp_prefs" style="width: 100%; border: 0px;" src="about:blank" scrolling="auto" border=0 frameborder=0></iframe></div>
<div id="chat_extra_body_mapp_sounds" style="display: none;"><iframe id="iframe_mapp_sounds" name="iframe_mapp_sounds" style="width: 100%; border: 0px;" src="about:blank" scrolling="auto" border=0 frameborder=0></iframe></div>
<div id="chat_extra_body_mapp_operators" style="display: none;"><iframe id="iframe_mapp_operators" name="iframe_mapp_operators" style="width: 100%; border: 0px;" src="about:blank" scrolling="auto" border=0 frameborder=0></iframe></div>
<div id="chat_extra_body_mapp_trans" style="display: none;"><iframe id="iframe_mapp_trans" name="iframe_mapp_trans" style="width: 100%; border: 0px;" src="../mapp/mapp_trans.php?ses=<?php echo $ses ?>&<?php echo $now ?>" scrolling="auto" border=0 frameborder=0></iframe></div>
<div id="chat_extra_body_mapp_power" style="display: none;"><iframe id="iframe_mapp_power" name="iframe_mapp_power" style="width: 100%; border: 0px;" src="about:blank" scrolling="auto" border=0 frameborder=0></iframe></div>
<div id="chat_extra_body_mapp_vinfo" style="display: none;"><iframe id="iframe_mapp_vinfo" name="iframe_mapp_vinfo" style="width: 100%; border: 0px;" src="../mapp/mapp_vinfo.php?ses=<?php echo $ses ?>&<?php echo $now ?>" scrolling="auto" border=0 frameborder=0></iframe></div>
<div id="chat_extra_body_mapp_cans" style="display: none;"><iframe id="iframe_mapp_cans" name="iframe_mapp_cans" style="width: 100%; border: 0px;" src="../mapp/mapp_canned.php?ses=<?php echo $ses ?>&<?php echo $now ?>" scrolling="auto" border=0 frameborder=0></iframe></div>